name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
<<<<<<< HEAD
version: 1.0.0-dev
=======
version: 1.0.0-dev.8.0
>>>>>>> 43b3755ab6885cefbc829d9c75a26c7f68263d0a
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
<<<<<<< HEAD
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  collection: ^1.14.6
  meta: ^1.1.0
  quill_delta: ^2.0.0
  quiver_hashcode: ^2.0.0
  tuple: ^2.0.0
=======
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  coverage: ^1.0.3
  quill_delta: ^3.0.0-nullsafety.1
  quiver: ^3.0.1
>>>>>>> 43b3755ab6885cefbc829d9c75a26c7f68263d0a

dev_dependencies:
  test: ^1.10.0
