name: notus
description: Platform-agnostic rich text document model based on Delta format and used in Zefyr editor.
version: 1.0.0-dev
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  quill_delta: ^3.0.0-nullsafety.2
  quiver_hashcode: ^3.0.0+1
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.19.3
