name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0-dev.2.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^6.0.9
  quill_delta: ^3.0.0-nullsafety.0
  notus:
    git:
      url: https://github.com/hokutoresident/zefyr
      ref: hokuto
      path: packages/notus
  quiver_hashcode: ^3.0.0+1
  characters: ^1.0.0
  google_fonts: 4.0.3
  validators: ^3.0.0
  kana_kit: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: lib/fonts/NotoSansJP-Regular.otf
          weight: 400
        - asset: lib/fonts/NotoSansJP-Bold.otf
          weight: 700

