name: milestone_check

on:
  pull_request:
    branches:
      - hokuto
    types: [closed]

env:
  WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  milestone_check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    timeout-minutes: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Send github comment
        if: ${{ github.event.pull_request.milestone == null }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ':warning: milestone(リリース番号)をつけてください :warning:'
            })
      - name: Send Slack Notification on Failure
        if: ${{ github.event.pull_request.milestone == null }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_WEBHOOK: ${{ env.WEBHOOK_URL }}
          SLACK_TITLE: Empty Milestone PR is merged
          SLACK_MESSAGE: |
            @${{ github.event.pull_request.user.login }}
            :no_entry_sign: milestoneのないPRがマージされました。

            下記のPRのmilestoneをつけてください。
            ${{ github.event.pull_request.html_url }}
          SLACK_COLOR: "#ff0000"
